/**
 * @author Camila Silva
 * @since Classe criada em 09/03/2022
 * Jogo dos oito utilizando Java
 * This class is main manager of the game
 */

//pacotes
package PuzzleGame;

//libraries
import java.util.Random;
import javax.swing.JButton;
import javax.swing.JOptionPane;

public class Game extends javax.swing.JFrame {

    //initializing components
    public Game() {
        initComponents();
           
        //calling the function to reset the game
        resetNumbers.resetGame(numberBtn1, numberBtn2, numberBtn3,
                                    numberBtn4, numberBtn5, numberBtn6,
                                     numberBtn7, numberBtn8, numberBtn9);
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     * 
     * JFrames objects criados na UI
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GamePanel = new javax.swing.JPanel();
        numberBtn1 = new javax.swing.JButton();
        numberBtn2 = new javax.swing.JButton();
        numberBtn3 = new javax.swing.JButton();
        numberBtn4 = new javax.swing.JButton();
        numberBtn5 = new javax.swing.JButton();
        numberBtn6 = new javax.swing.JButton();
        numberBtn7 = new javax.swing.JButton();
        numberBtn8 = new javax.swing.JButton();
        numberBtn9 = new javax.swing.JButton();
        titleTxt = new javax.swing.JLabel();
        clicksTxt = new javax.swing.JLabel();
        resetBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 51, 51));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(java.awt.Color.black);
        setName("main"); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        GamePanel.setBackground(new java.awt.Color(108, 76, 48));
        GamePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GamePanelMouseClicked(evt);
            }
        });

        numberBtn1.setBackground(new java.awt.Color(60, 28, 0));
        numberBtn1.setFont(new java.awt.Font("DialogInput", 0, 36)); // NOI18N
        numberBtn1.setForeground(new java.awt.Color(255, 255, 255));
        numberBtn1.setText("1");
        numberBtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                numberBtn1MouseClicked(evt);
            }
        });
        numberBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberBtn1ActionPerformed(evt);
            }
        });

        numberBtn2.setBackground(new java.awt.Color(59, 28, 0));
        numberBtn2.setFont(new java.awt.Font("DialogInput", 0, 36)); // NOI18N
        numberBtn2.setForeground(new java.awt.Color(255, 255, 255));
        numberBtn2.setText("2");
        numberBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberBtn2ActionPerformed(evt);
            }
        });

        numberBtn3.setBackground(new java.awt.Color(59, 28, 0));
        numberBtn3.setFont(new java.awt.Font("DialogInput", 0, 36)); // NOI18N
        numberBtn3.setForeground(new java.awt.Color(255, 255, 255));
        numberBtn3.setText("3");
        numberBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberBtn3ActionPerformed(evt);
            }
        });

        numberBtn4.setBackground(new java.awt.Color(59, 28, 0));
        numberBtn4.setFont(new java.awt.Font("DialogInput", 0, 36)); // NOI18N
        numberBtn4.setForeground(new java.awt.Color(255, 255, 255));
        numberBtn4.setText("4");
        numberBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberBtn4ActionPerformed(evt);
            }
        });

        numberBtn5.setBackground(new java.awt.Color(59, 28, 0));
        numberBtn5.setFont(new java.awt.Font("DialogInput", 0, 36)); // NOI18N
        numberBtn5.setForeground(new java.awt.Color(255, 255, 255));
        numberBtn5.setText("5");
        numberBtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberBtn5ActionPerformed(evt);
            }
        });

        numberBtn6.setBackground(new java.awt.Color(59, 28, 0));
        numberBtn6.setFont(new java.awt.Font("DialogInput", 0, 36)); // NOI18N
        numberBtn6.setForeground(new java.awt.Color(255, 255, 255));
        numberBtn6.setText("6");
        numberBtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberBtn6ActionPerformed(evt);
            }
        });

        numberBtn7.setBackground(new java.awt.Color(59, 28, 0));
        numberBtn7.setFont(new java.awt.Font("DialogInput", 0, 36)); // NOI18N
        numberBtn7.setForeground(new java.awt.Color(255, 255, 255));
        numberBtn7.setText("7");
        numberBtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberBtn7ActionPerformed(evt);
            }
        });

        numberBtn8.setBackground(new java.awt.Color(59, 28, 0));
        numberBtn8.setFont(new java.awt.Font("DialogInput", 0, 36)); // NOI18N
        numberBtn8.setForeground(new java.awt.Color(255, 255, 255));
        numberBtn8.setText("8");
        numberBtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberBtn8ActionPerformed(evt);
            }
        });

        numberBtn9.setBackground(new java.awt.Color(59, 28, 0));
        numberBtn9.setFont(new java.awt.Font("DialogInput", 0, 36)); // NOI18N
        numberBtn9.setForeground(new java.awt.Color(255, 255, 255));
        numberBtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberBtn9ActionPerformed(evt);
            }
        });

        titleTxt.setBackground(new java.awt.Color(255, 255, 255));
        titleTxt.setFont(new java.awt.Font("Digifit", 1, 36)); // NOI18N
        titleTxt.setForeground(new java.awt.Color(0, 0, 0));
        titleTxt.setText("   8-PUZZLE ");

        clicksTxt.setBackground(new java.awt.Color(108, 76, 48));
        clicksTxt.setFont(new java.awt.Font("Dialog", 1, 29)); // NOI18N
        clicksTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        clicksTxt.setText("0");

        resetBtn.setBackground(new java.awt.Color(59, 28, 0));
        resetBtn.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        resetBtn.setForeground(new java.awt.Color(0, 0, 0));
        resetBtn.setText("RESET");
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout GamePanelLayout = new javax.swing.GroupLayout(GamePanel);
        GamePanel.setLayout(GamePanelLayout);
        GamePanelLayout.setHorizontalGroup(
            GamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GamePanelLayout.createSequentialGroup()
                .addGroup(GamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GamePanelLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(GamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(GamePanelLayout.createSequentialGroup()
                                .addGroup(GamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(numberBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(numberBtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(numberBtn7, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(GamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(GamePanelLayout.createSequentialGroup()
                                        .addComponent(numberBtn8, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(numberBtn9, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(GamePanelLayout.createSequentialGroup()
                                        .addComponent(numberBtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(numberBtn6, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(GamePanelLayout.createSequentialGroup()
                                        .addComponent(numberBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(numberBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(GamePanelLayout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(clicksTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(resetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(GamePanelLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(titleTxt)))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        GamePanelLayout.setVerticalGroup(
            GamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GamePanelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(titleTxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(GamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numberBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numberBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numberBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(GamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numberBtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numberBtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numberBtn6, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(GamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(GamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(numberBtn7, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(numberBtn8, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(numberBtn9, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(GamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clicksTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        getContentPane().add(GamePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 430, 430));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

       
    
 //############################################  
    //the code start here
    

    //instantiating outer class
    Mouse mouseActions = new Mouse();
    
    Numbers changeNumbers = new Numbers();       
    
    Reset resetNumbers = new Reset();

 
    ////button actions number 7
    private void numberBtn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberBtn7ActionPerformed
        
        //getting random values of the slots
        changeNumbers.ChangingNumbers(numberBtn7, numberBtn4);
        changeNumbers.ChangingNumbers(numberBtn7, numberBtn8);
        
        //call function to checking the mouse click
        mouseActions.MouseClick(clicksTxt);
        
    }//GEN-LAST:event_numberBtn7ActionPerformed

    //button actions number 1
    private void numberBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberBtn1ActionPerformed
                     
        //getting random values of the slots
        changeNumbers.ChangingNumbers(numberBtn1, numberBtn2);
        changeNumbers.ChangingNumbers(numberBtn1, numberBtn4);
        
        //call function to checking the mouse click
        mouseActions.MouseClick(clicksTxt);
        
    }//GEN-LAST:event_numberBtn1ActionPerformed

    //button actions number 2
    private void numberBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberBtn2ActionPerformed
              
        //getting random values of the slots
        changeNumbers.ChangingNumbers(numberBtn2, numberBtn1);
        changeNumbers.ChangingNumbers(numberBtn2, numberBtn3);
        changeNumbers.ChangingNumbers(numberBtn2, numberBtn5);
        
        //call function to checking the mouse click
        mouseActions.MouseClick(clicksTxt);
    }//GEN-LAST:event_numberBtn2ActionPerformed

    //button actions number 3
    private void numberBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberBtn3ActionPerformed
        
        //getting random values of the slots
        changeNumbers.ChangingNumbers(numberBtn3, numberBtn2);
        changeNumbers.ChangingNumbers(numberBtn3, numberBtn6);
        
        //call function to checking the mouse click
        mouseActions.MouseClick(clicksTxt);
       
    }//GEN-LAST:event_numberBtn3ActionPerformed

    //button actions number 4
    private void numberBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberBtn4ActionPerformed
        
        //getting random values of the slots
        changeNumbers.ChangingNumbers(numberBtn4, numberBtn1);
        changeNumbers.ChangingNumbers(numberBtn4, numberBtn5);
        changeNumbers.ChangingNumbers(numberBtn4, numberBtn7);
        
        //call function to checking the mouse click
        mouseActions.MouseClick(clicksTxt);
    }//GEN-LAST:event_numberBtn4ActionPerformed

    //button actions number 5
    private void numberBtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberBtn5ActionPerformed
        
        //getting random values of the slots
        changeNumbers.ChangingNumbers(numberBtn5, numberBtn4);
        changeNumbers.ChangingNumbers(numberBtn5, numberBtn2);
        changeNumbers.ChangingNumbers(numberBtn5, numberBtn6);
        changeNumbers.ChangingNumbers(numberBtn5, numberBtn8);
        
        //call function to checking the mouse click
        mouseActions.MouseClick(clicksTxt);
        
    }//GEN-LAST:event_numberBtn5ActionPerformed

    //button actions number 6
    private void numberBtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberBtn6ActionPerformed
        
        //getting random values of the slots
        changeNumbers.ChangingNumbers(numberBtn6, numberBtn3);
        changeNumbers.ChangingNumbers(numberBtn6, numberBtn5);
        changeNumbers.ChangingNumbers(numberBtn6, numberBtn9);
        
        //call function to checking the mouse click
        mouseActions.MouseClick(clicksTxt);
        
    }//GEN-LAST:event_numberBtn6ActionPerformed

    //button actions number 9
    private void numberBtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberBtn9ActionPerformed
        
        //getting random values of the slots
        changeNumbers.ChangingNumbers(numberBtn9, numberBtn6);
        changeNumbers.ChangingNumbers(numberBtn9, numberBtn8);
        
        //call function to checking the mouse click            
        mouseActions.MouseClick(clicksTxt);
        
    }//GEN-LAST:event_numberBtn9ActionPerformed

    //button actions number 8
    private void numberBtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberBtn8ActionPerformed
        
        //getting random values of the slots
        changeNumbers.ChangingNumbers(numberBtn8, numberBtn7);
        changeNumbers.ChangingNumbers(numberBtn8, numberBtn5);
        changeNumbers.ChangingNumbers(numberBtn8, numberBtn9);
        
        //call function to checking the mouse click
        mouseActions.MouseClick(clicksTxt);
        
    }//GEN-LAST:event_numberBtn8ActionPerformed

    //button to shuffle the numbers
    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        
        //calling the function to reset the game
        resetNumbers.resetGame(numberBtn1, numberBtn2, numberBtn3,
                                    numberBtn4, numberBtn5, numberBtn6,
                                     numberBtn7, numberBtn8, numberBtn9);
        
        
        
        //resetNumbers.resetGame(Btn[numberBtn]);
                                     
        
         
        //calling function to reset the amounth
        mouseActions.ResetMouseClick(clicksTxt);
        
    }//GEN-LAST:event_resetBtnActionPerformed

    private void GamePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GamePanelMouseClicked
        
        
    }//GEN-LAST:event_GamePanelMouseClicked

    private void numberBtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_numberBtn1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_numberBtn1MouseClicked

  
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                 
                new Game().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel GamePanel;
    private javax.swing.JLabel clicksTxt;
    private javax.swing.JButton numberBtn1;
    private javax.swing.JButton numberBtn2;
    private javax.swing.JButton numberBtn3;
    private javax.swing.JButton numberBtn4;
    private javax.swing.JButton numberBtn5;
    private javax.swing.JButton numberBtn6;
    private javax.swing.JButton numberBtn7;
    private javax.swing.JButton numberBtn8;
    private javax.swing.JButton numberBtn9;
    private javax.swing.JButton resetBtn;
    private javax.swing.JLabel titleTxt;
    // End of variables declaration//GEN-END:variables
}
